// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3c-4nZIItSbqrefAw7JJVW3BWomnmylU',
    appId: '1:40223308121:web:70634327119d0435acb448',
    messagingSenderId: '40223308121',
    projectId: 'appfirebase-8470f',
    authDomain: 'appfirebase-8470f.firebaseapp.com',
    storageBucket: 'appfirebase-8470f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkoHvOdDQFaIfb2RaedQLHYxHdQPcrp-o',
    appId: '1:40223308121:android:f200fae0d50c5d4cacb448',
    messagingSenderId: '40223308121',
    projectId: 'appfirebase-8470f',
    storageBucket: 'appfirebase-8470f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm4mXBNObFLathvjV_x1Oy5Es-KfnpsB0',
    appId: '1:40223308121:ios:3b44157b08dd9f0aacb448',
    messagingSenderId: '40223308121',
    projectId: 'appfirebase-8470f',
    storageBucket: 'appfirebase-8470f.firebasestorage.app',
    iosBundleId: 'com.example.appFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm4mXBNObFLathvjV_x1Oy5Es-KfnpsB0',
    appId: '1:40223308121:ios:3b44157b08dd9f0aacb448',
    messagingSenderId: '40223308121',
    projectId: 'appfirebase-8470f',
    storageBucket: 'appfirebase-8470f.firebasestorage.app',
    iosBundleId: 'com.example.appFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3c-4nZIItSbqrefAw7JJVW3BWomnmylU',
    appId: '1:40223308121:web:0e1a9b5d1f44bb95acb448',
    messagingSenderId: '40223308121',
    projectId: 'appfirebase-8470f',
    authDomain: 'appfirebase-8470f.firebaseapp.com',
    storageBucket: 'appfirebase-8470f.firebasestorage.app',
  );
}
